# Generated by Django 5.2.5 on 2025-08-24 14:11

import awizacje.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='Firma')),
                ('delivery_date', models.DateField(verbose_name='Data dostawy')),
                ('delivery_type', models.CharField(choices=[('Dostawa paczka', 'Dostawa paczka'), ('Dostawa luz', 'Dostawa luz'), ('Dostawa kontener', 'Dostawa kontener'), ('Dostawa palety', 'Dostawa palety')], max_length=32, verbose_name='Typ dostawy')),
                ('hu_paleta', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Paleta')),
                ('hu_karton', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Karton')),
                ('hu_kontener', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Kontener')),
                ('driver_name', models.CharField(blank=True, max_length=120, verbose_name='Imię i nazwisko kierowcy')),
                ('driver_phone', models.CharField(blank=True, max_length=32, verbose_name='Telefon kierowcy')),
                ('truck_no', models.CharField(blank=True, max_length=32, verbose_name='Nr auta (ciągnik)')),
                ('trailer_no', models.CharField(blank=True, max_length=32, verbose_name='Nr naczepy')),
                ('order_no', models.CharField(blank=True, max_length=64, verbose_name='Numer zamówienia')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/', validators=[awizacje.models.validate_filesize_10mb], verbose_name='Załącznik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
